spring:
    profiles:
        active: local

# local
---
spring:
    profiles: local
    h2:
        console:
            enabled: true
            path: /test_db

    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:file:D:/work/test_db;AUTO_SERVER=true;MV_STORE=FALSE
        username: admin
        password: 1234
        data: classpath:data-h2.sql
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create-drop
