spring:
    h2:
        console:
            enabled: true
            path: /test_db

    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:file:D:/work/test_db;AUTO_SERVER=true
        username: admin
        password: 1234
